---
title: Advanced Regression Models
layout: default
---
## Advanced Regression Models

Each of the regression analysis below contains working code examples with brief use-case explanations covered for each of the regression types in the list below. Many of these code snippets are generic enough so you could use them as a base template to start and build up on for your analyses.

Please note that the information presented in these pages should not be construed as full and complete analysis, but rather as a template and a hand guide of available modeling options. You are advised to pursue independent and thorough research before arriving at conclusions.

METHOD	                                            | APPLICATION CASE
--------------------------------------------------- | --------------------------------------------
<a href="Robust-Regression-With-R.html">Robust Regression</a>	                                | Applicable in all cases where OLS regression can be used. Applies re-weighting to reduce outlier influence.
<a href="Logistic-Regression-With-R.html">Logistic Regression</a>	                                | Models binary variables.
<a href="Probit-Regression-With-R.html">Probit Regression</a>							| Models binary variables.
<a href="Multinomial-Regression-With-R.html">Multinomial Regression</a>						| Models categorical variables with more that 2 levels.
<a href="Ordinal-Logistic-Regression-With-R.html">Ordinal Logistic</a>				| Models ordinal or rank variables.
<a href="Poisson-and-Negative-Binomial-Regression-With-R.html">Poisson and Negative Binomial</a>	| Models count variables. Neg Binomial is used when there is over-dispersion.
<a href="Ridge-Regression-With-R.html">Ridge Regression</a>									| Address Multicollinearity
<a href="Beta-Regression-With-R.html">Beta Regression</a>										| Models variables within (0, 1) range.
<a href="Dirichlet-Regression-With-R.html">Dirichlet Regression</a>								| Models compositional data
<a href="Loess-Regression-With-R.html">Loess Regression</a>									| Smoothing Time series.
<a href="Isotonic-Regression-With-R.html">Isotonic Regression</a>									| For approximation of data that can only increase (..typically cumulative data)
