---
title: Ggplot2 Cheatsheet
layout: default
---

# Ggplot2 Cheatsheet

#### Basics tasks
* [Basic plot setup](ggplot2-cheatsheet.html#Basic plot setup)
* [Scatterplot](ggplot2-cheatsheet.html#Scatterplot)
* [Static - point size, shape, color and boundary thickness](ggplot2-cheatsheet.html#Static - point size, shape, color and boundary thickness)
* [Dynamic - point size, shape, color and boundary thickness](ggplot2-cheatsheet.html#Dynamic - point size, shape, color and boundary thickness)
* [Add title, X and Y axis labels](ggplot2-cheatsheet.html#Add Title, X and Y axis labels)
* [Change color of all text](ggplot2-cheatsheet.html#Change color of all text)
* [Change title, X and Y axis label size](ggplot2-cheatsheet.html#Change title, X and Y axis label size)
* [Change title font, face, color, line height](ggplot2-cheatsheet.html#Change title font, face, color, line height)
* [Adjust X and Y axis limits](ggplot2-cheatsheet.html#Adjust X and Y axis limits)
* [Flip X and Y axis](ggplot2-cheatsheet.html#Flip X and Y Axis)
* [Rotate axis text](ggplot2-cheatsheet.html#Rotate axis text)

#### Legend
* [Hide legend](ggplot2-cheatsheet.html#Hide legend)
* [Change legend position](ggplot2-cheatsheet.html#Change legend position)
* [Change legend title](ggplot2-cheatsheet.html#Change legend title)
* [Change legend text](ggplot2-cheatsheet.html#Change legend text)
* [Legend title and text size](ggplot2-cheatsheet.html#Legend title and text size)
* [Legend box color](ggplot2-cheatsheet.html#Legend box color)
* [Legend symbol size](ggplot2-cheatsheet.html#Legend symbol size)

#### Plot text and annotation
* [Annotation](ggplot2-cheatsheet.html#Annotation)
* [Add text in chart](ggplot2-cheatsheet.html#Add text in chart)

#### Multiple plots
* [Multiple chart panels](ggplot2-cheatsheet.html#Multiple chart panels)
* [Free X and Y axis scales](ggplot2-cheatsheet.html#Free X and Y axis scales)
* [Arrange multiple plots](ggplot2-cheatsheet.html#Arrange multiple plots)

#### Geom layers
* [Add smoothing line](ggplot2-cheatsheet.html#Add smoothing line)
* [Add horizontal / vertical line](ggplot2-cheatsheet.html#Add horizontal / vertical line)
* [Add bar chart](ggplot2-cheatsheet.html#Add bar chart)
* [Grouped bar chart](ggplot2-cheatsheet.html#Grouped bar chart)
* [Distinct color for bars]((ggplot2-cheatsheet.html#Distinct color for bars)
* [Change color of bars](ggplot2-cheatsheet.html#Change color of bars)
* [Change color palette](ggplot2-cheatsheet.html#Change color palette)
* [Make line chart](ggplot2-cheatsheet.html#Make line chart)
* [Add multiple lines](ggplot2-cheatsheet.html#Add multiple lines)
* [Line chart from timeseries](ggplot2-cheatsheet.html#Line chart from timeseries)


## Basic tasks

##### Basic plot setup
  
	gg <- ggplot(df, aes(x=xcol, y=ycol)) 
	`df` must be a dataframe that contains all information to make the ggplot. Plot will show up only after adding the geom layers.

##### Scatterplot
  
  	gg + geom_point()

##### Static - point size, shape, color and boundary thickness
  
    gg + geom_point(size=1, shape=1, color="steelblue", stroke=2)

##### Dynamic - point size, shape, color and boundary thickness
  
    gg + geom_point(aes(size=1, shape=1, color="steelblue", stroke=2))            

##### Add Title, X and Y axis labels
  
    gg1 <- gg + geom_point() + labs(title="Plot Title", x="X-Axis", y="Y-Axis")

##### Change color of all text
  
    gg1 + theme(text=element_text(color="blue"))

##### Change title, X and Y axis label size
  
    gg1 + theme(plot.title=element_text(size=25), axis.title.x=element_text(size=20), axis.title.y=element_text(size=20))

##### Change title font, face, color, line height

    gg1 + theme(plot.title=element_text(family="calibri", face="bold", color="steelblue", lineheight=1.5)

##### Adjust X and Y axis limits

    Method 1: Zoom in
    gg1 + coord_cartesian(xlim=c(x1,x2), ylim=c(y1, y2))
    
    Method 2: Deletes the points outside limits
    gg1 + xlim(c(x1,x2)) + ylim(c(y1,y2)))
    
    Method 3: Deletes the points outside limits
    gg1 + scale_x_continuous(limits=c(x1,x2)) + scale_y_continuous(limits=c(y1,y2))
    
##### Flip X and Y Axis

    gg1 + coord_flip()

##### Rotate axis text

    gg1 + theme(axis.text.x=element_text(angle=45), axis.text.y=element_text(angle=45))
  
## Legend

##### Hide legend
  
    gg1 + theme(legend.postion="none")

##### Change legend title
  
    gg1 + scale_color_discrete(name="Cut of diamonds")

##### Change legend text
  
    scale_colour_manual(name='', values=c('Important line'='grey', 'Point values'='red'))

##### Change legend position
  
    Method 1: Outside plot
    gg1 + theme(legend.postion="top")  # top / bottom / left / right
    
    Method 2: Inside plot
    gg1 + theme(legend.justification=c(1,0), legend.position=c(1,0))
  
##### Legend title and text size
  
    gg1 + theme(legend.title = element_text(size=20), legend.text = element_text(size=15))
  
##### Legend box color
  
    gg1 + theme(legend.key=element_rect(fill='steelblue'))
    
##### Legend symbol size
    
    gg1 + guides(colour = guide_legend(override.aes = list(size=4)))

## Plot text and annotation

##### Annotation
  
    gg1 + geom_text(aes(xcol, ycol, label=round(labelCol), size=3)
  
##### Add text in chart
  
    gg1 + annotate("mytext", x=xpos, y=ypos, label="My text")

    library(grid)
    my_grob = grobTree(textGrob("My Custom Text", x=0.1, y=0.9, gp=gpar(col="firebrick", fontsize=25, fontface="bold")))
    GG1 + annotation_custom(my_grob)


## Multiple plots

##### Multiple chart panels
  
    gg1 + facet_wrap(rowVariable ~ columnVariable, ncol=2)  # multiple plots 
    gg1 + facet_grid(rowVariable ~ columnVariable)  # arrange in a grid. More space for plots.
  
##### Free X and Y axis scales
  
    gg1 + facet_wrap(rowVariable ~ columnVariable, ncol=2, scales="free")  # free the x and y axis scales.
  
##### Arrange multiple plots
    
    library(gridExtra)
    grid.arrange(gg1, gg2, gg3, ncol=2)


## Geom layers

##### Add smoothing line
  
    gg + geom_smooth(method="lm")  # method could be - 'lm', 'loess', 'gam'
  
##### Add horizontal / vertical line

    gg + geom_hline(yintercept=10)
    gg + geom_vline(xintercept=10)

##### Add bar chart
    gg <- ggplot(df, aes(x=xcol))
    gg1 <- ggplot(df, aes(x=xcol, y=ycol))  
    gg + geom_bar()  # frequency table
    gg1 + geom_bar(stat="identity")  # static bar chart
    
##### Grouped bar chart 

    gg1 + geom_bar(stat="identity", position="dodge", fill=groupcol)  # without 'dodge', bars will be stacked.

##### Distinct color for bars
    
    gg1 + geom_bar(stat="identity", aes(fill=colorVariable))

##### Change color of bars
    
    gg1 + geom_bar(stat="identity") + scale_fill_manual(values=c("color1", "color2", "color3"))

##### Change color palette
    
    library(RColorBrewer)
    display.brewer.all(n=20, exact.n=FALSE)  # display available color palettes
    ggplot(mtcars, aes(x=cyl, y=carb, fill=factor(cyl))) + geom_bar(stat="identity") + scale_fill_brewer(palette="Reds")  # "Reds" is palette name

##### Make line chart
  
    gg + geom_line(linetype='dotted', size=1, color="firebrick")  # linetypes: solid, dashed, dotted, dotdash, longdash and twodash
    gg + geom_line(linetype='dotted', aes(size=sizeVar, color=colorVar))  # dynamic size and color.
  
##### Add multiple lines

    Method 1:
    gg + geom_line(aes(x=date, y=yVar, color=colorVar)) + geom_line(aes(x=date, y=yVar2, col=colorVar2)) + scale_color_discrete(name="Legend") 
    
    Method 2:
    library(reshape2)
    df <- melt(economics[, c("date", "pce", "unemploy")], id="date")
    ggplot(df) + geom_line(aes(x=date, y=value, color=variable)) + labs(title="Economics")# plot multiple time series by melting

##### Line chart from timeseries
  
    library(ggfortify)
    autoplot(tsobject)

