---
layout: default
title: Tutorials on Advanced Stats and Machine Learning With R
---

# Welcome to r-statistics.co

An educational resource for those seeking knowledge related to machine learning and statistical computing in R.
Here, you will find quality articles, with working R code and examples, where, the goal is to make the [#rstats](http://bit.ly/2kyJ31C) concepts clear and as simple as possible. 

This is built by keeping in mind, statisticians who are new to R programming language, R programmers without a stats background, analysts who work in SAS or python, college grads and developers who are relatively new to both R and stats/ML. If you are completely new to R, this [R tutorial](R-Tutorial.html) is a good place it start.

#### Video Courses
[Learn R By Intensive Practice](http://bit.ly/2mb2IDf): Gain clear understanding of base R programming concepts and internalise through a lot of practice.

[Introduction to R Programming](http://bit.ly/2apjNXo): Covers core programming with R, statistics fundamentals, base graphics, data manipulation with data.table and dplyr. (For Beginners)

[Mastering R Programming](http://bit.ly/2jDsrGS): Covers advanced machine learning concepts and interesting programming exercises throughout the [course](http://bit.ly/2jDsrGS). (For Data scientists and Machine Learning Engineers)



```{r, echo = FALSE}
embed_png("screenshots/corrplot2.png", dpi=220)
```

<!--
<ul class="toc">
  {% include programming-nav.html %}
</ul>
-->