---
title: Linear Regression Simplified
layout: default
output: bookdown::html_chapter
---

> Linear regression is a fundamental predictive modelling technique that aims to predict the value of an outcome variable based on  one or more input predictor variables. The aim is to establish a linear relationship (a mathematical formula) between the predictor variable(s) and the response variable, so we can use it to estimate the value of the response, when predictors values are known.

##Introduction

For this analysis, we will use the ‘cars’ dataset that comes with R by default. ‘cars’ is a standard built-in dataset, that makes it convenient to demonstrate linear regression in a simple and easy to understand fashion. You can access this dataset simply by typing in ‘cars’ in your R console. You will find that it consists of 50 observations(rows) and 2 variables (columns) – Dist and Speed. Lets print out the first six observations here..

```{r echo = TRUE, eval = TRUE}
head(cars)  # display the first 6 observations
```